version: "3"

services:
  mongo:
    image: mongo
    volumes:
      - "../mongo-data:/data/db"
    ports:
      - 127.0.0.1:27017:27017

  mongo-express:
    image: mongo-express
    links:
      - mongo
    ports:
      - 8080:8081
